// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5U835DKNlgp72HelCLrcv3A2Q3dzYuSo',
    appId: '1:218635889450:web:10381a571b1eb05cee8c53',
    messagingSenderId: '218635889450',
    projectId: 'chat-app-80155',
    authDomain: 'chat-app-80155.firebaseapp.com',
    storageBucket: 'chat-app-80155.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxKHe4WUlM041a2NfILLx9P4UrEE14LCw',
    appId: '1:218635889450:android:751f7c46cf33ca17ee8c53',
    messagingSenderId: '218635889450',
    projectId: 'chat-app-80155',
    storageBucket: 'chat-app-80155.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9bT32YJBsugzV1f0pBtgM75H0KE7_HaM',
    appId: '1:218635889450:ios:967f3bb01b77b377ee8c53',
    messagingSenderId: '218635889450',
    projectId: 'chat-app-80155',
    storageBucket: 'chat-app-80155.appspot.com',
    iosBundleId: 'com.example.schoolerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9bT32YJBsugzV1f0pBtgM75H0KE7_HaM',
    appId: '1:218635889450:ios:2fd02226457d1937ee8c53',
    messagingSenderId: '218635889450',
    projectId: 'chat-app-80155',
    storageBucket: 'chat-app-80155.appspot.com',
    iosBundleId: 'com.example.schoolerApp.RunnerTests',
  );
}
